name: New Feature
description: Set a story
title: '[Feature]: '
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: feature-name
    attributes:
      label: Feature name
      description: Describe what you want to see
      placeholder: what you see!
      value: User story
    validations:
      required: true
