name: New Feature
description: Set a story
title: 'Feature: '
labels: ['feature']
body:
  - type: textarea
    id: Description
    attributes:
      label: Description
      description: Describe what you want to see
      placeholder: what you see!
      value: User story
    validations:
      required: true
